#!/bin/bash

mv ~/.gitconfig ~/.gitconfig.original
cp .gitconfig ~/.gitconfig

mv ~/.gitignore ~/.gitignore.original
cp .gitignore ~/.gitignore

mv ~/.zshrc ~/.zshrc.original
cp .zshrc ~/.zshrc

mv ~/.zshenv ~/.zshenv.original
cp .zshenv ~/.zshenv

mv ~/.oh-my-zsh/themes/sayanee.zsh-theme ~/.oh-my-zsh/themes/sayanee.zsh-theme.original
cp sayanee.zsh-theme ~/.oh-my-zsh/themes/sayanee.zsh-theme

mv ~/.atom/config.cson ~/.atom/config.cson.original
cp config.cson ~/.atom/config.cson

mv /etc/hosts /etc/hosts.original
cp hosts /etc/hosts
